import type { PlaceApi } from '@leblanc/shared';

export const placeFixture: PlaceApi = {
  id: 'a1000000-0000-4000-8000-000000000001',
  type: 'restaurant',
  subtypes: ['Restaurant'],
  title_i18n: { fr: 'La Table' },
  description_i18n: { fr: 'Cuisine locale' },
  sourceLanguage: 'fr',
  venueName: null,
  address: '1 rue du Centre',
  postalCode: '36300',
  city: 'Le Blanc',
  latitude: 46.6333,
  longitude: 1.0833,
  phone: null,
  email: null,
  website: null,
  imageUrl: null,
  publicUrl: null,
  cuisines: ['TraditionalCuisine'],
  priceRangeMin: 15,
  priceRangeMax: 30,
  currency: 'EUR',
  priceDetails: [],
  takeaway: null,
  openingHoursStatus: 'unknown',
  status: 'published',
  normalizedTitle: 'la table',
  title: 'La Table',
  description: 'Cuisine locale',
  contentLanguage: 'fr',
  isFallback: false,
  distance: 1500,
  source: 'datatourisme_places',
  openingHours: [],
  isOpenNow: null,
};
